stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: |-
        mkdir -p /go/src/github.com/rancher1
        ln -s `pwd` /go/src/github.com/rancher1/pipeline-example-go
        cd /go/src/github.com/rancher1/pipeline-example-go
        go build -o bin/hello-server
        go test -cover
    env:
      http_proxy: http://172.18.192.4:8080
      https_proxy: http://172.18.192.4:8080
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-helloserver:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification: {}
